/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memorytest;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yujian
 */
public class RankingJFrame extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form RankingJFrame
     */
    public RankingJFrame(int difficulty) {
        initComponents();
        this.difficulty = difficulty;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initValue();
        initAction();
    }
    
    private void initValue(){
        dtm.setColumnIdentifiers(new String[]{"姓名","成绩(秒)","记录时间"});
        jtblShow.setModel(dtm);
        jtblShow.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jtblShow.getColumnModel().getColumn(0).setPreferredWidth(90);
        jtblShow.getColumnModel().getColumn(1).setPreferredWidth(90);
        jtblShow.getColumnModel().getColumn(2).setPreferredWidth(jtblShow.getWidth()-180);
    }
    
    private void initAction(){
        jbtnShowRanking.addActionListener(this);
        jbtnCleanRanking.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnShowRanking = new javax.swing.JButton();
        jbtnCleanRanking = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblShow = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnShowRanking.setText("显示排行榜");

        jbtnCleanRanking.setText("清空排行榜");

        jtblShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblShow.setEnabled(false);
        jScrollPane2.setViewportView(jtblShow);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jbtnShowRanking)
                .addGap(36, 36, 36)
                .addComponent(jbtnCleanRanking)
                .addContainerGap(73, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCleanRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnShowRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnCleanRanking;
    private javax.swing.JButton jbtnShowRanking;
    private javax.swing.JTable jtblShow;
    // End of variables declaration//GEN-END:variables
    private int difficulty;
    private DefaultTableModel dtm = new DefaultTableModel();

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==jbtnShowRanking){
            SqlServer sqlServer = new SqlServer();
            dtm.setRowCount(0);
            sqlServer.selectBydifficulty(difficulty, dtm);
            sqlServer.close();
            return;
        }
        if(e.getSource()==jbtnCleanRanking){
            int res = JOptionPane.showConfirmDialog(null,
                    "是否确认清空排行榜",
                    "提示框",
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.WARNING_MESSAGE);
            if(res==JOptionPane.YES_OPTION){
                System.out.println("yes");
                SqlServer sqlServer = new SqlServer();
                dtm.setRowCount(0);
                sqlServer.delete(difficulty);
                sqlServer.selectBydifficulty(difficulty, dtm);
                sqlServer.close();
            }
            else{
                System.out.println("no"); 
            }
            return;
        }
    }
}
