/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memorytest;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JOptionPane;

/**
 *
 * @author yujian
 */
public class RecordJFrame extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form RecordJFrame
     */
    public RecordJFrame(Ranking ranking,MainJFrame mainJFrame) {
        initComponents();
        this.ranking = ranking;
        this.mainJFrame = mainJFrame;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initValue();
        initAction();
    }
    
    private void initValue(){
        switch(ranking.getDifficulty()){
            case 0:
                jlblShow.setText("输入你的姓名，将成绩存放到排行榜：初级记忆排行榜.txt");
                break;
            case 1:
                jlblShow.setText("输入你的姓名，将成绩存放到排行榜：中级记忆排行榜.txt");
                break;
            case 2:
                jlblShow.setText("输入你的姓名，将成绩存放到排行榜：高级级记忆排行榜.txt");
                break;
        }
    }
    
    private void initAction(){
        jbtnConfirm.addActionListener(this);
        jbtnCancel.addActionListener(this);
        this.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                reset();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblShow = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jbtnConfirm = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblShow.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jlblShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblShow.setText("输入你的姓名，将成绩存放到排行榜：初级记忆排行榜.txt");
        jlblShow.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("姓名");

        jtfName.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jtfName.setText("匿名");

        jbtnConfirm.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jbtnConfirm.setText("确定");

        jbtnCancel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jbtnCancel.setText("取消");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jbtnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jlblShow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnConfirm;
    private javax.swing.JLabel jlblShow;
    private javax.swing.JTextField jtfName;
    // End of variables declaration//GEN-END:variables
    private Ranking ranking;
    private MainJFrame mainJFrame;

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==jbtnConfirm){
            if(jtfName.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null,
                    "请输入名字！",
                    "提示框",
                    JOptionPane.ERROR_MESSAGE);
            }
            else{
                ranking.setName(jtfName.getText());
                SqlServer sqlServer = new SqlServer();
                sqlServer.insert(ranking);
                sqlServer.close();
                this.setVisible(false);
                reset();
            }
            return;
        }
        if(e.getSource()==jbtnCancel){
            this.setVisible(false);
            reset();
            return;
        }
    }
    
    //将主界面进行复位
    private void reset(){
        switch(ranking.getDifficulty()){
            case 0:
                mainJFrame.primary();
                break;
            case 1:
                mainJFrame.intermediate();
                break;
            case 2:
                mainJFrame.senior();
                break;
        }
    }
}
